const { test } = require('node:test');
const assert = require('node:assert');
const { extractRecipes, generateSkillContent } = require('../lib/generator.js');

test('extractRecipes - simple recipes', () => {
  const justfileData = {
    recipes: {
      build: {
        name: 'build',
        namepath: 'build',
        doc: 'Build the project',
        parameters: [],
        private: false
      },
      test: {
        name: 'test',
        namepath: 'test',
        doc: 'Run tests',
        parameters: [],
        private: false
      }
    }
  };

  const recipes = extractRecipes(justfileData);

  assert.strictEqual(recipes.length, 2);
  assert.strictEqual(recipes[0].name, 'build');
  assert.strictEqual(recipes[0].doc, 'Build the project');
  assert.strictEqual(recipes[1].name, 'test');
});

test('extractRecipes - filter private recipes', () => {
  const justfileData = {
    recipes: {
      build: {
        name: 'build',
        namepath: 'build',
        doc: 'Build the project',
        parameters: [],
        private: false
      },
      _private: {
        name: '_private',
        namepath: '_private',
        doc: 'Private helper',
        parameters: [],
        private: true
      }
    }
  };

  const recipes = extractRecipes(justfileData);

  assert.strictEqual(recipes.length, 1);
  assert.strictEqual(recipes[0].name, 'build');
});

test('extractRecipes - recipes with parameters', () => {
  const justfileData = {
    recipes: {
      deploy: {
        name: 'deploy',
        namepath: 'deploy',
        doc: 'Deploy application',
        parameters: [
          { name: 'target', default: null },
          { name: 'port', default: '8080' }
        ],
        private: false
      }
    }
  };

  const recipes = extractRecipes(justfileData);

  assert.strictEqual(recipes.length, 1);
  assert.strictEqual(recipes[0].parameters.length, 2);
  assert.strictEqual(recipes[0].parameters[0].name, 'target');
  assert.strictEqual(recipes[0].parameters[0].required, true);
  assert.strictEqual(recipes[0].parameters[1].name, 'port');
  assert.strictEqual(recipes[0].parameters[1].required, false);
  assert.strictEqual(recipes[0].parameters[1].default, '8080');
});

test('extractRecipes - module recipes', () => {
  const justfileData = {
    recipes: {
      build: {
        name: 'build',
        namepath: 'build',
        doc: 'Build main',
        parameters: [],
        private: false
      }
    },
    modules: {
      subdir: {
        recipes: {
          deploy: {
            name: 'deploy',
            namepath: 'subdir::deploy',
            doc: 'Deploy subdir',
            parameters: [],
            private: false
          }
        }
      }
    }
  };

  const recipes = extractRecipes(justfileData);

  assert.strictEqual(recipes.length, 2);
  assert.strictEqual(recipes[0].name, 'build');
  assert.strictEqual(recipes[0].modulePath.length, 0);
  assert.strictEqual(recipes[1].name, 'deploy');
  assert.strictEqual(recipes[1].namepath, 'subdir::deploy');
  assert.strictEqual(recipes[1].modulePath.length, 1);
  assert.strictEqual(recipes[1].modulePath[0], 'subdir');
});

test('generateSkillContent - simple recipe', () => {
  const recipe = {
    name: 'build',
    namepath: 'build',
    doc: 'Build the project',
    parameters: [],
    modulePath: []
  };

  const content = generateSkillContent(recipe);

  assert.ok(content.includes('---'));
  assert.ok(content.includes('name: just-build'));
  assert.ok(content.includes('description: Build the project'));
  assert.ok(content.includes('# Justfile Recipe: build'));
  assert.ok(content.includes('just build'));
  assert.ok(content.includes('<!-- Generated by just-claude'));
});

test('generateSkillContent - recipe with parameters', () => {
  const recipe = {
    name: 'deploy',
    namepath: 'deploy',
    doc: 'Deploy application',
    parameters: [
      { name: 'target', required: true },
      { name: 'port', required: false, default: '8080' }
    ],
    modulePath: []
  };

  const content = generateSkillContent(recipe);

  assert.ok(content.includes('just deploy <target> [port]'));
  assert.ok(content.includes('**target** (required)'));
  assert.ok(content.includes('**port** (optional, default: "8080")'));
});

test('generateSkillContent - module recipe', () => {
  const recipe = {
    name: 'deploy',
    namepath: 'subdir::deploy',
    doc: 'Deploy from subdir',
    parameters: [],
    modulePath: ['subdir']
  };

  const content = generateSkillContent(recipe);

  assert.ok(content.includes('name: just-subdir-deploy'));
  assert.ok(content.includes('just subdir::deploy'));
});
