#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

/**
 * Parse justfile JSON and extract recipe information
 * @param {Object} justfileData - Parsed JSON from `just --dump --dump-format json`
 * @returns {Array} Array of recipe objects
 */
function extractRecipes(justfileData, modulePath = []) {
  const recipes = [];

  // Extract recipes from current level
  if (justfileData.recipes) {
    for (const [recipeName, recipeData] of Object.entries(justfileData.recipes)) {
      // Skip private recipes (starting with _)
      if (recipeData.private) {
        continue;
      }

      // Extract parameters
      const params = (recipeData.parameters || []).map(param => ({
        name: param.name,
        required: param.default === null,
        default: param.default
      }));

      recipes.push({
        name: recipeName,
        namepath: recipeData.namepath || recipeName,
        doc: recipeData.doc || '',
        parameters: params,
        modulePath: modulePath
      });
    }
  }

  // Recursively extract from modules
  if (justfileData.modules) {
    for (const [moduleName, moduleData] of Object.entries(justfileData.modules)) {
      const moduleRecipes = extractRecipes(moduleData, [...modulePath, moduleName]);
      recipes.push(...moduleRecipes);
    }
  }

  return recipes;
}

/**
 * Generate skill directory name from recipe
 * @param {Object} recipe - Recipe object
 * @returns {string} Skill directory path
 */
function getSkillPath(recipe, skillsDir) {
  if (recipe.modulePath.length === 0) {
    // Root recipe: .claude/skills/just-<recipe-name>
    return path.join(skillsDir, `just-${recipe.name}`);
  } else {
    // Module recipe: .claude/skills/just-<module>/<recipe-name>
    return path.join(skillsDir, `just-${recipe.modulePath.join('/')}`, recipe.name);
  }
}

/**
 * Generate skill markdown content
 * @param {Object} recipe - Recipe object
 * @returns {string} SKILL.md content
 */
function generateSkillContent(recipe) {
  const lines = [];

  // YAML frontmatter
  const description = recipe.doc || `Run ${recipe.name} recipe`;
  lines.push('---');
  lines.push(`name: just-${recipe.namepath.replace('::', '-')}`);
  lines.push(`description: ${description}`);
  lines.push('---');
  lines.push('');

  // Generated marker
  lines.push('<!-- Generated by just-claude - Do not edit manually -->');
  lines.push('');

  // Recipe title
  lines.push(`# Justfile Recipe: ${recipe.name}`);
  lines.push('');

  // Doc comment if present
  if (recipe.doc) {
    lines.push(recipe.doc);
    lines.push('');
  }

  // Usage
  lines.push('## Usage');
  if (recipe.parameters.length === 0) {
    lines.push(`just ${recipe.namepath}`);
  } else {
    const paramStr = recipe.parameters.map(p =>
      p.required ? `<${p.name}>` : `[${p.name}]`
    ).join(' ');
    lines.push(`just ${recipe.namepath} ${paramStr}`);
  }
  lines.push('');

  // Parameters section
  if (recipe.parameters.length > 0) {
    lines.push('## Parameters');
    for (const param of recipe.parameters) {
      if (param.required) {
        lines.push(`- **${param.name}** (required)`);
      } else {
        lines.push(`- **${param.name}** (optional, default: "${param.default}")`);
      }
    }
    lines.push('');
  } else {
    lines.push('## Parameters');
    lines.push('None');
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Check if a skill was generated by just-claude
 * @param {string} skillPath - Path to skill directory
 * @returns {boolean}
 */
function isGeneratedSkill(skillPath) {
  const skillFile = path.join(skillPath, 'SKILL.md');
  if (!fs.existsSync(skillFile)) {
    return false;
  }

  const content = fs.readFileSync(skillFile, 'utf-8');
  return content.includes('<!-- Generated by just-claude');
}

/**
 * Generate skills from justfile data
 * @param {string} projectRoot - Project root directory
 * @param {Object} justfileData - Parsed justfile JSON
 */
function generateSkills(projectRoot, justfileData) {
  const skillsDir = path.join(projectRoot, '.claude', 'skills');

  // Extract all recipes
  const recipes = extractRecipes(justfileData);

  if (recipes.length === 0) {
    console.log('just-claude: No public recipes found in justfile');
    return;
  }

  // Create skills directory if needed
  if (!fs.existsSync(skillsDir)) {
    fs.mkdirSync(skillsDir, { recursive: true });
  }

  let generated = 0;
  let skipped = 0;

  for (const recipe of recipes) {
    const skillPath = getSkillPath(recipe, skillsDir);
    const skillFile = path.join(skillPath, 'SKILL.md');

    // Check if skill exists and wasn't generated by us
    if (fs.existsSync(skillPath) && !isGeneratedSkill(skillPath)) {
      console.log(`just-claude: Skipping ${recipe.namepath} - manual skill exists`);
      skipped++;
      continue;
    }

    // Create skill directory
    fs.mkdirSync(skillPath, { recursive: true });

    // Generate SKILL.md
    const content = generateSkillContent(recipe);
    fs.writeFileSync(skillFile, content, 'utf-8');

    generated++;
  }

  console.log(`just-claude: Generated ${generated} skill(s) from justfile`);
  if (skipped > 0) {
    console.log(`just-claude: Skipped ${skipped} skill(s) with manual definitions`);
  }
}

/**
 * Clean up generated skills
 * @param {string} projectRoot - Project root directory
 */
function cleanSkills(projectRoot) {
  const skillsDir = path.join(projectRoot, '.claude', 'skills');

  if (!fs.existsSync(skillsDir)) {
    return;
  }

  let cleaned = 0;

  // Find all just-* directories
  const entries = fs.readdirSync(skillsDir, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.isDirectory() && entry.name.startsWith('just-')) {
      const skillPath = path.join(skillsDir, entry.name);

      // Only remove if it was generated by us
      if (isGeneratedSkill(skillPath)) {
        fs.rmSync(skillPath, { recursive: true, force: true });
        cleaned++;
      }
    }
  }

  console.log(`just-claude: Cleaned ${cleaned} generated skill(s)`);
}

/**
 * List generated skills
 * @param {string} projectRoot - Project root directory
 */
function listSkills(projectRoot) {
  const skillsDir = path.join(projectRoot, '.claude', 'skills');

  if (!fs.existsSync(skillsDir)) {
    console.log('No skills directory found');
    return;
  }

  const entries = fs.readdirSync(skillsDir, { withFileTypes: true });
  const skills = [];

  for (const entry of entries) {
    if (entry.isDirectory() && entry.name.startsWith('just-')) {
      const skillPath = path.join(skillsDir, entry.name);
      if (isGeneratedSkill(skillPath)) {
        skills.push(entry.name);
      }
    }
  }

  if (skills.length === 0) {
    console.log('No generated just-claude skills found');
  } else {
    console.log('Generated skills:');
    for (const skill of skills) {
      console.log(`  - ${skill}`);
    }
  }
}

// Main entry point
if (require.main === module) {
  const projectRoot = process.argv[2] || process.cwd();
  const justfileJson = process.argv[3];

  if (!justfileJson) {
    console.error('Usage: generator.js <project-root> <justfile-json>');
    process.exit(1);
  }

  try {
    const justfileData = JSON.parse(justfileJson);
    generateSkills(projectRoot, justfileData);
  } catch (error) {
    console.error('just-claude: Error generating skills:', error.message);
    process.exit(0); // Don't block Claude Code
  }
}

module.exports = {
  extractRecipes,
  generateSkills,
  cleanSkills,
  listSkills,
  getSkillPath,
  generateSkillContent,
  isGeneratedSkill
};
