#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

/**
 * Get the project root directory
 */
function getProjectRoot() {
  return process.env.INIT_CWD || process.cwd();
}

/**
 * Remove hook script
 */
function removeHookScript(projectRoot) {
  const hookFile = path.join(projectRoot, '.claude', 'hooks', 'detect-justfile.sh');

  if (fs.existsSync(hookFile)) {
    fs.unlinkSync(hookFile);
    console.log('just-claude: Removed hook script');
  }
}

/**
 * Clean up generated skills
 */
function cleanupSkills(projectRoot) {
  const skillsDir = path.join(projectRoot, '.claude', 'skills');

  if (!fs.existsSync(skillsDir)) {
    return;
  }

  let cleaned = 0;

  try {
    const entries = fs.readdirSync(skillsDir, { withFileTypes: true });

    for (const entry of entries) {
      if (entry.isDirectory() && entry.name.startsWith('just-')) {
        const skillPath = path.join(skillsDir, entry.name);
        const skillFile = path.join(skillPath, 'SKILL.md');

        // Only remove if it was generated by us
        if (fs.existsSync(skillFile)) {
          const content = fs.readFileSync(skillFile, 'utf-8');
          if (content.includes('<!-- Generated by just-claude')) {
            fs.rmSync(skillPath, { recursive: true, force: true });
            cleaned++;
          }
        }
      }
    }

    if (cleaned > 0) {
      console.log(`just-claude: Removed ${cleaned} generated skill(s)`);
    }
  } catch (error) {
    console.error('just-claude: Error cleaning skills:', error.message);
  }
}

/**
 * Remove hook configuration from settings.json
 */
function unconfigureSettings(projectRoot) {
  const settingsFile = path.join(projectRoot, '.claude', 'settings.json');
  const backupFile = path.join(projectRoot, '.claude', 'settings.json.backup');

  if (!fs.existsSync(settingsFile)) {
    return;
  }

  try {
    const content = fs.readFileSync(settingsFile, 'utf-8');
    const settings = JSON.parse(content);

    if (!Array.isArray(settings.hooks)) {
      return;
    }

    // Remove our SessionStart hook
    const originalLength = settings.hooks.length;
    settings.hooks = settings.hooks.filter(hook => {
      if (hook.type !== 'SessionStart') {
        return true;
      }

      // Keep if it doesn't reference our hook script
      if (!hook.hooks || !Array.isArray(hook.hooks)) {
        return true;
      }

      return !hook.hooks.some(h =>
        h.command && h.command.includes('detect-justfile.sh')
      );
    });

    const removed = originalLength - settings.hooks.length;

    if (removed > 0) {
      // Check if hooks array is now empty
      if (settings.hooks.length === 0) {
        // Restore backup if it exists
        if (fs.existsSync(backupFile)) {
          fs.copyFileSync(backupFile, settingsFile);
          fs.unlinkSync(backupFile);
          console.log('just-claude: Restored original settings.json');
        } else {
          // No backup, just remove our empty hooks array
          delete settings.hooks;
          fs.writeFileSync(settingsFile, JSON.stringify(settings, null, 2) + '\n', 'utf-8');
          console.log('just-claude: Removed hook configuration');
        }
      } else {
        // Other hooks exist, just write updated settings
        fs.writeFileSync(settingsFile, JSON.stringify(settings, null, 2) + '\n', 'utf-8');
        console.log('just-claude: Removed hook configuration');

        // Clean up backup
        if (fs.existsSync(backupFile)) {
          fs.unlinkSync(backupFile);
        }
      }
    }
  } catch (error) {
    console.error('just-claude: Error updating settings.json:', error.message);
  }
}

/**
 * Main uninstallation function
 */
function uninstall() {
  try {
    const projectRoot = getProjectRoot();

    console.log('just-claude: Uninstalling...');

    removeHookScript(projectRoot);
    cleanupSkills(projectRoot);
    unconfigureSettings(projectRoot);

    console.log('just-claude: Uninstallation complete!');
  } catch (error) {
    console.error('just-claude: Uninstallation error:', error.message);
    process.exit(0); // Don't fail npm uninstall
  }
}

// Run uninstallation
uninstall();
