#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

/**
 * Get the project root directory
 */
function getProjectRoot() {
  return process.env.INIT_CWD || process.cwd();
}

/**
 * Remove hook script
 */
function removeHookScript(projectRoot) {
  const hookFile = path.join(projectRoot, '.claude', 'hooks', 'detect-justfile.sh');

  if (fs.existsSync(hookFile)) {
    fs.unlinkSync(hookFile);
    console.log('just-claude: Removed hook script');
  }
}

/**
 * Clean up generated skills
 */
function cleanupSkills(projectRoot) {
  const skillsDir = path.join(projectRoot, '.claude', 'skills');

  if (!fs.existsSync(skillsDir)) {
    return;
  }

  let cleaned = 0;

  try {
    const entries = fs.readdirSync(skillsDir, { withFileTypes: true });

    for (const entry of entries) {
      if (entry.isDirectory() && entry.name.startsWith('just-')) {
        const skillPath = path.join(skillsDir, entry.name);
        const skillFile = path.join(skillPath, 'SKILL.md');

        // Only remove if it was generated by us
        if (fs.existsSync(skillFile)) {
          const content = fs.readFileSync(skillFile, 'utf-8');
          if (content.includes('<!-- Generated by just-claude')) {
            fs.rmSync(skillPath, { recursive: true, force: true });
            cleaned++;
          }
        }
      }
    }

    if (cleaned > 0) {
      console.log(`just-claude: Removed ${cleaned} generated skill(s)`);
    }
  } catch (error) {
    console.error('just-claude: Error cleaning skills:', error.message);
  }
}

/**
 * Remove hook configuration from settings.json
 */
function unconfigureSettings(projectRoot) {
  const settingsFile = path.join(projectRoot, '.claude', 'settings.json');
  const backupFile = path.join(projectRoot, '.claude', 'settings.json.backup');
  const claudeDir = path.join(projectRoot, '.claude');

  if (!fs.existsSync(settingsFile)) {
    return;
  }

  try {
    // If backup exists, restore it and clean up
    if (fs.existsSync(backupFile)) {
      fs.copyFileSync(backupFile, settingsFile);
      fs.unlinkSync(backupFile);
      console.log('just-claude: Restored original settings.json');
      return;
    }

    const content = fs.readFileSync(settingsFile, 'utf-8');
    const settings = JSON.parse(content);

    // Normalize hooks shape
    if (!settings.hooks || typeof settings.hooks !== 'object') {
      return;
    }

    // Remove our SessionStart hook(s)
    const sessionHooks = Array.isArray(settings.hooks.SessionStart) ? settings.hooks.SessionStart : [];
    const filteredSessionHooks = sessionHooks.filter(entry => {
      if (!entry.hooks || !Array.isArray(entry.hooks)) return true;
      return !entry.hooks.some(h => h.command && h.command.includes('detect-justfile.sh'));
    });

    const removed = sessionHooks.length - filteredSessionHooks.length;

    settings.hooks.SessionStart = filteredSessionHooks;
    if (settings.hooks.SessionStart.length === 0) {
      delete settings.hooks.SessionStart;
    }

    // If hooks is now empty, remove it
    if (Object.keys(settings.hooks).length === 0) {
      delete settings.hooks;
    }

    if (removed > 0) {
      // If settings now empty, remove the file
      if (Object.keys(settings).length === 0) {
        fs.unlinkSync(settingsFile);
        console.log('just-claude: Removed settings.json');
      } else {
        fs.writeFileSync(settingsFile, JSON.stringify(settings, null, 2) + '\n', 'utf-8');
        console.log('just-claude: Removed hook configuration');
      }
    }

    // Clean up empty .claude directory
    try {
      const remaining = fs.readdirSync(claudeDir);
      if (remaining.length === 0) {
        fs.rmdirSync(claudeDir);
      }
    } catch {
      // ignore
    }
  } catch (error) {
    console.error('just-claude: Error updating settings.json:', error.message);
  }
}

/**
 * Main uninstallation function
 */
function uninstall() {
  try {
    const projectRoot = getProjectRoot();

    console.log('just-claude: Uninstalling...');

    removeHookScript(projectRoot);
    cleanupSkills(projectRoot);
    unconfigureSettings(projectRoot);

    console.log('just-claude: Uninstallation complete!');
  } catch (error) {
    console.error('just-claude: Uninstallation error:', error.message);
    process.exit(0); // Don't fail npm uninstall
  }
}

// Run uninstallation
uninstall();
